"""indexes

Revision ID: 830f578467c1
Revises: 8847c0204ad3
Create Date: 2021-12-02 22:22:15.671723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830f578467c1'
down_revision = '8847c0204ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_title_key', 'chat', type_='unique')
    op.create_index(op.f('ix_chat_title'), 'chat', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_title'), table_name='chat')
    op.create_unique_constraint('chat_title_key', 'chat', ['title'])
    # ### end Alembic commands ###
