"""change foreignkey add indexes

Revision ID: 8847c0204ad3
Revises: 37c7135b2e47
Create Date: 2021-11-27 22:35:37.393706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8847c0204ad3'
down_revision = '37c7135b2e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_uuid_key', 'chat', type_='unique')
    op.create_index(op.f('ix_chat_uuid'), 'chat', ['uuid'], unique=True)
    op.add_column('message', sa.Column('chat_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('message_uuid_key', 'message', type_='unique')
    op.create_index(op.f('ix_message_uuid'), 'message', ['uuid'], unique=True)
    op.drop_constraint('message_chat_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'chat', ['chat_uuid'], ['uuid'])
    op.drop_column('message', 'chat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_chat_id_fkey', 'message', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_message_uuid'), table_name='message')
    op.create_unique_constraint('message_uuid_key', 'message', ['uuid'])
    op.drop_column('message', 'chat_uuid')
    op.drop_index(op.f('ix_chat_uuid'), table_name='chat')
    op.create_unique_constraint('chat_uuid_key', 'chat', ['uuid'])
    # ### end Alembic commands ###
